POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Quincy Larson",
  "url": "https://www.freecodecamp.org/news/podcast-biggest-youtube-programming-channel-beau-carnes/",
  "title": "Podcast: Running the Biggest Programming Channel on YouTube with freeCodeCamp's Beau Carnes",
  "likes" : 101
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Beau Carnes",
  "title": "Learn React and Tailwind CSS for Front End Development",
  "likes" : 51
}

###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/100


###
PUT http://localhost:3001/api/blogs/200
Content-Type: application/json

{
  "likes" : 200
}

###
DELETE  http://localhost:3001/api/blogs/4

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name" : "Liyon SV",
  "username" : "leon"
}

###
GET http://localhost:3001/api/users

###
PUT http://localhost:3001/api/users/leon
Content-Type: application/json

{
  "username" : "leonsv"
}


