POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a test note",
  "important": true,
  "date": "2025-08-09T10:00:00Z"
}

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": true,
  "date": "2025-08-09T10:00:00Z"
}

###
PUT http://localhost:3001/api/notes/1
Content-Type: application/json

{
  "important": false,
  "date": "2025-08-09T10:00:00Z"
}


